### ISSUE TITLE
Help Customizing Datapack

### ISSUE THREAD

**Issue by sherpascott** [ForestMinecraft/Forest-s-Datapacks-Resource-Packs#1]
Hey I just want to add on to the double deep slate drops datapack to make stone iron ore only drop a nugget to force people to dive into caves longer to get iron. How would I do that? I tried to edit the data pack but it didn’t work I’m just not familiar with datapack editing.

**Comment by ForestMinecraft** [comment]
I would recommend asking for help on the [Datapack Hub](https://discord.gg/WfdgGD4x) Discord server.
